SELECT * 
--, count(1) over(PARTITION BY CUSTOMER_ID) AS prefs
FROM VK_DATA.CUSTOMERS.CUSTOMER_SURVEY
--ORDER BY prefs desc


WITH cust_tags AS 
(SELECT cd.CUSTOMER_ID , cd.FIRST_NAME , cd.LAST_NAME , cd.EMAIL , (TAGS.TAG_PROPERTY ) customer_tag, count(1) OVER (PARTITION BY cd.CUSTOMER_ID ORDER BY trim(TAGS.TAG_PROPERTY )) AS TAG_RANK
FROM VK_DATA.RESOURCES.RECIPE_TAGS TAGS 
	JOIN VK_DATA.CUSTOMERS.CUSTOMER_SURVEY survey 
		ON TAGS.TAG_ID = SURVEY.TAG_ID AND is_active
	JOIN VK_DATA.CUSTOMERS.CUSTOMER_DATA cd ON cd.CUSTOMER_ID = SURVEY.CUSTOMER_ID 
		INNER JOIN VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca ON cd.CUSTOMER_ID = ca.CUSTOMER_ID 
	JOIN VK_DATA.RESOURCES.US_CITIES ctys ON 
		(upper(trim(ca.CUSTOMER_CITY)) = UPPER( ctys.CITY_NAME)
	AND upper(trim(ca.CUSTOMER_STATE)) = upper(ctys.STATE_ABBR))
QUALIFY TAG_RANK <=3
ORDER BY 1)
,recipe_tags AS 
(SELECT RECIPE_NAME , (replace(T.VALUE, '"','')) AS tag_word
FROM VK_DATA.CHEFS.RECIPE r , TABLE(flatten(r.TAG_LIST)) T)
, customer_prefs AS 
(SELECT  * FROM 
cust_tags
pivot(min(customer_tag) FOR TAG_RANK IN (1,2,3)) AS pivot_values(CUSTOMER_ID,FIRST_NAME, LAST_NAME, EMAIL, food_pref_1, food_pref_2, food_pref_3))
, customer_recipe AS
(
SELECT customer_id, any_value(rt.RECIPE_NAME) AS RECIPE
FROM cust_tags ct JOIN recipe_tags rt ON ct.customer_tag = rt.tag_word AND ct.tag_rank = 1
GROUP BY 1
)

SELECT *
FROM customer_prefs cpref JOIN customer_recipe cr ON cpref.customer_id = cr.customer_id
ORDER BY email



SELECT *
--cd.CUSTOMER_ID , cd.FIRST_NAME , cd.LAST_NAME , cd.EMAIL , (TAGS.TAG_PROPERTY ) customer_tag, count(1) OVER (PARTITION BY cd.CUSTOMER_ID ORDER BY trim(TAGS.TAG_PROPERTY )) AS TAG_RANK
FROM VK_DATA.RESOURCES.RECIPE_TAGS TAGS 
	JOIN VK_DATA.CUSTOMERS.CUSTOMER_SURVEY survey 
		ON TAGS.TAG_ID = SURVEY.TAG_ID AND is_active
	JOIN VK_DATA.CUSTOMERS.CUSTOMER_DATA cd ON cd.CUSTOMER_ID = SURVEY.CUSTOMER_ID 
		INNER JOIN VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca ON cd.CUSTOMER_ID = ca.CUSTOMER_ID 
	JOIN VK_DATA.RESOURCES.US_CITIES ctys ON 
		(upper(trim(ca.CUSTOMER_CITY)) = UPPER( ctys.CITY_NAME)
	AND upper(trim(ca.CUSTOMER_STATE)) = upper(ctys.STATE_ABBR))
WHERE cd.CUSTOMER_ID = '07d191dc-ed55-470f-88c6-ffee7fe84a13'


SELECT r.* , (replace(T.VALUE, '"','')) AS tag_word
FROM VK_DATA.CHEFS.RECIPE r , TABLE(flatten(r.TAG_LIST)) T
WHERE T.VALUE LIKE '% reynolds-wrap%'

 reynolds-wrap


07d191dc-ed55-470f-88c6-ffee7fe84a13

 reynolds-wrap

SELECT 
cpref.*, cr.recipe
FROM customer_prefs cpref JOIN customer_recipe cr ON cpref.customer_id = cr.customer_id
ORDER BY cpref.email


WITH recipe_tags AS 
(SELECT RECIPE_NAME , trim(replace(T.VALUE, '"','')) AS tag_word
FROM VK_DATA.CHEFS.RECIPE r , TABLE(flatten(r.TAG_LIST)) T)

SELECT * FROM recipe_tags WHERE tag_word = 'cookies-and-brownies'


 african

[
  "60-minutes-or-less",
  " time-to-make",
  " course",
  " preparation",
  " appetizers"
]




-- QUESTION 1

WITH suppliers_data AS 
(SELECT
	SUP_INF.SUPPLIER_ID , SUP_INF.SUPPLIER_NAME , SUP_INF.SUPPLIER_CITY , SUP_INF.SUPPLIER_STATE , ctys.LAT , ctys.LONG 
FROM
	VK_DATA.SUPPLIERS.SUPPLIER_INFO sup_inf
LEFT JOIN VK_DATA.RESOURCES.US_CITIES ctys ON
	upper(SUP_INF.SUPPLIER_CITY) = ctys.CITY_NAME
	AND upper(SUP_INF.SUPPLIER_STATE) = ctys.STATE_ABBR)
, cities AS 
(

SELECT ctys.CITY_NAME, ctys.STATE_ABBR , ctys.LAT , ctys.LONG 
FROM VK_DATA.RESOURCES.US_CITIES ctys
QUALIFY ROW_NUMBER() OVER (PARTITION BY ctys.CITY_NAME, ctys.STATE_ABBR ORDER BY ctys.COUNTY_NAME) = 1
)
, customers_data AS
(
SELECT cd.CUSTOMER_ID , cd.FIRST_NAME ,cd.LAST_NAME , ca.CUSTOMER_CITY , ca.CUSTOMER_STATE , ca.CUSTOMER_POSTAL_CODE , ctys.LAT , ctys.LONG , cd.EMAIL 
FROM VK_DATA.CUSTOMERS.CUSTOMER_DATA cd 
	INNER JOIN VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca ON cd.CUSTOMER_ID = ca.CUSTOMER_ID
	  JOIN cities ctys ON
	((upper(trim(ca.CUSTOMER_CITY)) = UPPER( ctys.CITY_NAME)
	AND upper(trim(ca.CUSTOMER_STATE)) = upper(ctys.STATE_ABBR))) 

	
)
,
distances AS 
(
SELECT CUSTOMER_ID, cd.first_name, cd.last_name,  SUPPLIER_ID,sd.SUPPLIER_NAME
, sd.LAT, cd.LAT, sd.LONG, cd.LONG
,cd.CUSTOMER_CITY , cd.CUSTOMER_STATE, sd.SUPPLIER_CITY , sd.SUPPLIER_STATE , cd.EMAIL,
(st_distance(
st_makepoint(cd.LONG,   cd.LAT),
    st_makepoint(sd.LONG, sd.LAT)
    
  ) /1609) as dist_in_kilometres
--, sqrt(SQUARE(sd.LAT-cd.LAT) + SQUARE(sd.LONG-cd.LONG)) distance
FROM suppliers_data sd CROSS JOIN customers_data cd 
QUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY dist_in_kilometres) = 1
)


SELECT CUSTOMER_ID AS "Customer ID", first_name AS "Customer first name",last_name AS  "Customer last name", EMAIL AS "Customer email"
	,SUPPLIER_ID "Supplier ID", SUPPLIER_NAME AS "Supplier name", dist_in_kilometres "Shipping distance Miles"
FROM distances ORDER BY 3,2;


-- Question 1 end ==






SELECT * FROM VK_DATA.CUSTOMERS.CUSTOMER_DATA c WHERE c.LAST_NAME LIKE '%breu'

SELECT * FROM VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS c WHERE c.CUSTOMER_ID = 'e1050a1a-5bc2-4811-875f-d6a705ee20a7'

Riverview     

SELECT * FROM VK_DATA.RESOURCES.US_CITIES u WHERE u.CITY_NAME = UPPER('Riverview') 


WITH customer_cities AS
(
SELECT DISTINCT UPPER(CUSTOMER_CITY) AS  CUSTOMER_CITY, CUSTOMER_STATE 
FROM VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS 
)
, matches AS 
(SELECT CUSTOMER_CITY, CUSTOMER_STATE 
FROM customer_cities cc JOIN VK_DATA.RESOURCES.US_CITIES cu ON cc.CUSTOMER_CITY = cu.CITY_NAME AND cc.CUSTOMER_STATE = cu.STATE_ABBR 
)

SELECT count(DISTINCT customer_id)
FROM VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca JOIN matches m ON upper(ca.CUSTOMER_CITY) = m.CUSTOMER_CITY AND ca.CUSTOMER_STATE = m.CUSTOMER_STATE 



SELECT count(ca.CUSTOMER_ID) , count(DISTINCT CUSTOMER_ID) 
FROM VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca


SELECT 
count(1) , count(city_id), count(DISTINCT CASE WHEN city_id IS NOT NULL THEN cd.CUSTOMER_ID ELSE NULL end) 
--cd.CUSTOMER_ID , cd.FIRST_NAME ,cd.LAST_NAME , ca.CUSTOMER_CITY , ca.CUSTOMER_STATE , ca.CUSTOMER_POSTAL_CODE , ctys.LAT , ctys.LONG , ctys.ZIPS , ctys.CITY_NAME , ctys.STATE_ABBR , ctys.STATE_NAME 
FROM VK_DATA.CUSTOMERS.CUSTOMER_DATA cd 
	INNER JOIN VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca ON cd.CUSTOMER_ID = ca.CUSTOMER_ID
	LEFT  JOIN VK_DATA.RESOURCES.US_CITIES ctys ON
	((upper(ca.CUSTOMER_CITY) = UPPER( ctys.CITY_NAME)
	AND upper(ca.CUSTOMER_STATE) = upper(ctys.STATE_ABBR)) )
WHERE  TRUE 

AND ctys.CITY_ID IS null


SELECT * FROM 


SELECT cd.CUSTOMER_ID , cd.FIRST_NAME ,cd.LAST_NAME , ca.CUSTOMER_CITY , ca.CUSTOMER_STATE , ca.CUSTOMER_POSTAL_CODE 
FROM VK_DATA.CUSTOMERS.CUSTOMER_DATA cd INNER JOIN VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS ca ON cd.CUSTOMER_ID = ca.CUSTOMER_ID  LIMIT 10;

SELECT * FROM VK_DATA.CUSTOMERS.CUSTOMER_ADDRESS a 

SELECT * , count(1) over(PARTITION BY CUSTOMER_ID) AS prefs
FROM VK_DATA.CUSTOMERS.CUSTOMER_SURVEY
ORDER BY prefs desc

SELECT * FROM INFORMATION_SCHEMA."COLUMNS" c WHERE c.COLUMN_NAME LIKE '%TAG%'


SELECT * FROM VK_DATA.RESOURCES.US_CITIES 

SELECT *, count(1) OVER (PARTITION BY CITY_NAME , STATE_ABBR) AS c_s
--count(1), count(DISTINCT CITY_NAME , STATE_ABBR )
FROM VK_DATA.RESOURCES.US_CITIES 
  QUALIFY count(1) OVER (PARTITION BY CITY_NAME , STATE_ABBR) > 1
ORDER BY CITY_NAME , STATE_ABBR

SELECT
	*
FROM
	VK_DATA.SUPPLIERS.SUPPLIER_INFO sup_inf
LEFT JOIN VK_DATA.RESOURCES.US_CITIES ctys ON
	upper(SUP_INF.SUPPLIER_CITY) = ctys.CITY_NAME
	AND upper(SUP_INF.SUPPLIER_STATE) = ctys.STATE_ABBR 

SELECT * FROM VK_DATA.RESOURCES.RECIPE_TAGS re